// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH8CXqQWtChG8dr_uteMzxqvicbS9g_Wk',
    appId: '1:243524203291:web:c251e07ca8dd992a1e19be',
    messagingSenderId: '243524203291',
    projectId: 'hats-7558f',
    authDomain: 'hats-7558f.firebaseapp.com',
    storageBucket: 'hats-7558f.appspot.com',
    measurementId: 'G-0JGZLZEMBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv6M50rMjDI0YY-M5CCtmk45M52GLL3sU',
    appId: '1:243524203291:android:8b7bc9cbca52f7e31e19be',
    messagingSenderId: '243524203291',
    projectId: 'hats-7558f',
    storageBucket: 'hats-7558f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaYZxH4aoizt5pSx_EL4gpOzC3qvqLkjI',
    appId: '1:243524203291:ios:ea3fde2ac84ac4a71e19be',
    messagingSenderId: '243524203291',
    projectId: 'hats-7558f',
    storageBucket: 'hats-7558f.appspot.com',
    iosBundleId: 'com.example.hats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaYZxH4aoizt5pSx_EL4gpOzC3qvqLkjI',
    appId: '1:243524203291:ios:73bb28e250f397d61e19be',
    messagingSenderId: '243524203291',
    projectId: 'hats-7558f',
    storageBucket: 'hats-7558f.appspot.com',
    iosBundleId: 'com.example.hats.RunnerTests',
  );
}
