class DatabaseAlreadyOpen implements Exception{}
class UnableToGet implements Exception{}
class NoDatabaseOpen implements Exception{}
class CouldNotDelete implements Exception{}
class UserAlreadyExists implements Exception{}
class CouldNotFindUser implements Exception{}
class CouldNotDeleteNote implements Exception{}
class CouldNotFindNote implements Exception{}
class CouldNotUpdateNote implements Exception{}
